services:
  db:
    image: mysql:8.0

    container_name: air_quality_mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: dev_root_password
      MYSQL_DATABASE: air_quality_db

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init:/docker-entrypoint-initdb.d
      - ./data:/data

    command: --local-infile=1 --secure-file-priv=""

volumes:
  mysql_data: