name: air_quality
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.2
  - numpy=1.26
  - geopandas=0.14
  - shapely=2.0
  - pyproj=3.6
  - requests=2.31
  - python-dotenv=1.0
  - sqlalchemy
  - pymysql