table purpleair_cleaned_wo_outliers
	lineageTag: 20081478-6e9f-4bdf-9265-f91efda6630b

	column Column1
		dataType: int64
		formatString: 0
		lineageTag: 1781e981-2c4b-4fa4-bedc-c6088f04e2ce
		summarizeBy: sum
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: dateTime
		formatString: General Date
		lineageTag: 095c2a07-f3cb-4abc-aed2-4c38f547beb8
		summarizeBy: none
		sourceColumn: Column2

		variation Variation
			isDefault
			relationship: 43a33d81-d968-422d-bfe8-00f2eece3d35
			defaultHierarchy: LocalDateTable_04662912-12f8-4a90-8e27-97135564f2be.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: int64
		formatString: 0
		lineageTag: a9020ba8-2405-481c-b13e-0957f4456e5a
		summarizeBy: sum
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: int64
		formatString: 0
		lineageTag: a01cc53c-1aa8-462d-98cd-9a8ed8f51c23
		summarizeBy: sum
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: double
		lineageTag: bc1a4816-9e49-4426-97fb-51a3d80c4bb6
		summarizeBy: sum
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column6
		dataType: double
		lineageTag: d8a5cbdc-7866-4e80-8891-3f4cae597a0b
		summarizeBy: sum
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column7
		dataType: double
		lineageTag: 2bc308ba-851f-40aa-b3be-835adc0dd11e
		summarizeBy: sum
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column8
		dataType: double
		lineageTag: 46b9d978-8918-49e1-8d85-76654673a5a2
		summarizeBy: sum
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition purpleair_cleaned_wo_outliers = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\juwri\Downloads\Air Quality Project\data\purpleair_cleaned_wo_outliers.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", Int64.Type}, {"Column2", type datetime}, {"Column3", Int64.Type}, {"Column4", Int64.Type}, {"Column5", type number}, {"Column6", type number}, {"Column7", type number}, {"Column8", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

